/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author akcha
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mngbooking = new javax.swing.JButton();
        checkin = new javax.swing.JButton();
        roominfo = new javax.swing.JButton();
        mngpay = new javax.swing.JButton();
        mngexp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mngbooking.setBackground(new java.awt.Color(255, 255, 255));
        mngbooking.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        mngbooking.setForeground(new java.awt.Color(0, 0, 0));
        mngbooking.setText("Manage Bookings");
        mngbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngbookingActionPerformed(evt);
            }
        });
        getContentPane().add(mngbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 130, 30));

        checkin.setBackground(new java.awt.Color(255, 255, 255));
        checkin.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        checkin.setForeground(new java.awt.Color(0, 0, 0));
        checkin.setText("Add Customer");
        checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinActionPerformed(evt);
            }
        });
        getContentPane().add(checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 140, 30));

        roominfo.setBackground(new java.awt.Color(255, 255, 255));
        roominfo.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        roominfo.setForeground(new java.awt.Color(0, 0, 0));
        roominfo.setText("View Room Info");
        roominfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roominfoActionPerformed(evt);
            }
        });
        getContentPane().add(roominfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 130, 30));

        mngpay.setBackground(new java.awt.Color(255, 255, 255));
        mngpay.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        mngpay.setForeground(new java.awt.Color(0, 0, 0));
        mngpay.setText("Manage Payment");
        mngpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngpayActionPerformed(evt);
            }
        });
        getContentPane().add(mngpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 140, 30));

        mngexp.setBackground(new java.awt.Color(255, 255, 255));
        mngexp.setFont(new java.awt.Font("Lato", 1, 12)); // NOI18N
        mngexp.setForeground(new java.awt.Color(0, 0, 0));
        mngexp.setText("Manage Expense");
        mngexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngexpActionPerformed(evt);
            }
        });
        getContentPane().add(mngexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 321, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/IMG_20210921_194603.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mngbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngbookingActionPerformed
        ManageBookings ab = new ManageBookings();
        ab.setVisible(true);
    }//GEN-LAST:event_mngbookingActionPerformed

    private void checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinActionPerformed
        AddCustomer ab = new AddCustomer();
        ab.setVisible(true);
    }//GEN-LAST:event_checkinActionPerformed

    private void roominfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roominfoActionPerformed
        ViewRoom ab = new ViewRoom();
        ab.setVisible(true);
    }//GEN-LAST:event_roominfoActionPerformed

    private void mngpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngpayActionPerformed
        ManagePayment ab = new ManagePayment();
        ab.setVisible(true);
    }//GEN-LAST:event_mngpayActionPerformed

    private void mngexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngexpActionPerformed
        ManageExpense ab = new ManageExpense();
        ab.setVisible(true);
    }//GEN-LAST:event_mngexpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mngbooking;
    private javax.swing.JButton mngexp;
    private javax.swing.JButton mngpay;
    private javax.swing.JButton roominfo;
    // End of variables declaration//GEN-END:variables
}
